-- Written in the SQL subset shared by PostgreSQL and H2, so tests run the exact production migration.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255)             NOT NULL,
    password_hash VARCHAR(100)             NOT NULL,
    full_name     VARCHAR(100)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE accounts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number     VARCHAR(20)              NOT NULL,
    owner_id   BIGINT                   NOT NULL REFERENCES users (id),
    currency   VARCHAR(3)               NOT NULL,
    name       VARCHAR(60)              NOT NULL,
    balance    NUMERIC(19, 2)           NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_accounts_number UNIQUE (number),
    -- Last line of defence: even a bug in the service layer cannot push a balance below zero.
    CONSTRAINT ck_accounts_balance_non_negative CHECK (balance >= 0)
);

CREATE INDEX ix_accounts_owner ON accounts (owner_id);

CREATE TABLE operations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            VARCHAR(16)              NOT NULL,
    from_account_id BIGINT REFERENCES accounts (id),
    to_account_id   BIGINT                   NOT NULL REFERENCES accounts (id),
    amount          NUMERIC(19, 2)           NOT NULL,
    currency        VARCHAR(3)               NOT NULL,
    description     VARCHAR(140),
    initiated_by    BIGINT                   NOT NULL REFERENCES users (id),
    idempotency_key VARCHAR(64),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_operations_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_operations_transfer_has_source CHECK (type <> 'TRANSFER' OR from_account_id IS NOT NULL),
    -- NULL keys never collide, so operations without a key are unaffected.
    CONSTRAINT uq_operations_idempotency UNIQUE (initiated_by, idempotency_key)
);

-- History is always "operations of these accounts, newest first".
CREATE INDEX ix_operations_from_account ON operations (from_account_id, created_at);
CREATE INDEX ix_operations_to_account ON operations (to_account_id, created_at);
